Protocol: NEC
Address: 0E0E0
Power:      040BF
Volume +:   0E01F
Volume -:   0D02F
Mute:       0F00F
Source:     0807F
Menu:       058A7
Up:         006F9
Down:       08679
Left:       0A659
Right:      046B9
OK/Enter:   016E9
